import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function EpisodeProfile() {
  const router = useRouter();
  const [data, setData] = useState({});

  useEffect(() => {
    fetch(`https://rickandmortyapi.com/api/episode/${router.query.pid}`)
      .then((res) => res.json())
      .then(async (res) => {
        if (res.characters?.length) {
          await fetch(
            `https://rickandmortyapi.com/api/character/${res.characters
              .map((characters) => characters.split("/").pop())
              .join(",")}`
          )
            .then((res) => res.json())
            .then((characters) => {
              console.log(characters)
              res.characters = Array.isArray(characters) ? characters : [characters]
            });
        }
        return res;
      })
      .then((res) => setData(res));
  }, []);

  console.log(data);

  return (
    <>
      <Head>
        <title>{data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
        <h1>{data.name}</h1>
        <div style={{ display: "grid", gridColumn: 2, gap: "10px" }}>
          <div
            style={{ display: "flex", flexDirection: "column", gap: "10px" }}
          >
            <h3>{data.air_date}</h3>
          </div>
          <div
            style={{ display: "flex", flexDirection: "column", gap: "10px" }}
          >
            <h3>Characters</h3>
            <div style={{ display:"flex", flexFlow:"row wrap", gap:"10px" }}>
              {data?.characters?.map((character) => (
                <Link key={character.id} href={`/characters/${character.id}`}>
                  <div>
                    <Image src={character.image} width={240} height={168} />
                    <p>{character.name}</p>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
